// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMtue_ENRXdS61UMNXU-dJ3WKoCbbtukg',
    appId: '1:857038862176:web:751bdb5d8ff2e1baadd005',
    messagingSenderId: '857038862176',
    projectId: 'digital-trust-app',
    authDomain: 'digital-trust-app.firebaseapp.com',
    storageBucket: 'digital-trust-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClrRxiF0IGNr8IvGU0f6Q34GaMVlSoDew',
    appId: '1:857038862176:android:fc50f1293f069f65add005',
    messagingSenderId: '857038862176',
    projectId: 'digital-trust-app',
    storageBucket: 'digital-trust-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IJtgIOCLKa7HkL_zFN29Zy3xh-2LkBQ',
    appId: '1:857038862176:ios:c5e559788d572e39add005',
    messagingSenderId: '857038862176',
    projectId: 'digital-trust-app',
    storageBucket: 'digital-trust-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0IJtgIOCLKa7HkL_zFN29Zy3xh-2LkBQ',
    appId: '1:857038862176:ios:c5e559788d572e39add005',
    messagingSenderId: '857038862176',
    projectId: 'digital-trust-app',
    storageBucket: 'digital-trust-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMtue_ENRXdS61UMNXU-dJ3WKoCbbtukg',
    appId: '1:857038862176:web:4bae53f5f5429d36add005',
    messagingSenderId: '857038862176',
    projectId: 'digital-trust-app',
    authDomain: 'digital-trust-app.firebaseapp.com',
    storageBucket: 'digital-trust-app.firebasestorage.app',
  );
}
